"""
Battle Tournament system — weekly seasons, 8-agent brackets.
"""
import os, uuid, random, asyncio, httpx
from fastapi import APIRouter, HTTPException, Header
from pydantic import BaseModel
from typing import Optional
from backend.database import get_conn
from backend.auth import get_user_by_token

router = APIRouter(prefix="/tournament", tags=["tournament"])

ADMIN_TOKEN = "cogit-admin-2026"
GROQ_URL    = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL  = "llama-3.3-70b-versatile"

SEASON_QUESTIONS: dict[str, list[str]] = {
    "ai":         ["Will AI assistants replace search engines?", "Is GPT-4 overhyped or underhyped?", "Can AI be truly creative or only recombinative?", "Should AI models be open-sourced by default?"],
    "coding":     ["Is TypeScript strictly better than JavaScript?", "Will no-code tools replace junior developers?", "Is microservices architecture overused?", "Should all code be AI-generated by 2030?"],
    "finance":    ["Is Bitcoin digital gold or digital tulips?", "Will passive investing outperform active over the next decade?", "Is the US dollar's reserve currency status at risk?", "Should central banks issue digital currencies?"],
    "blockchain": ["Will DeFi replace traditional banking?", "Are NFTs dead or evolving?", "Is Ethereum or Bitcoin the better long-term store of value?", "Will blockchain ever achieve mainstream adoption?"],
    "science":    ["Is reversing aging achievable within 20 years?", "Should we terraform Mars before fixing Earth?", "Is nuclear energy the key to climate solutions?", "Will quantum computing break modern encryption within 10 years?"],
    "security":   ["Is zero-trust security achievable in practice?", "Should governments mandate security audits for all software?", "Is AI better or worse for cybersecurity net-net?", "Should ethical hacking be taught in schools?"],
}


@router.get("")
def list_tournaments():
    """List active and recent tournaments."""
    conn = get_conn()
    rows = conn.execute("""
        SELECT t.*,
               COUNT(DISTINCT tm.id) as match_count,
               COUNT(DISTINCT CASE WHEN tm.status='done' THEN tm.id END) as done_count
        FROM tournaments t
        LEFT JOIN tournament_matches tm ON tm.tournament_id = t.id
        GROUP BY t.id
        ORDER BY t.started_at DESC
        LIMIT 10
    """).fetchall()
    conn.close()
    return [dict(r) for r in rows]


@router.get("/{tournament_id}")
def get_tournament(tournament_id: str):
    """Get full tournament bracket."""
    conn = get_conn()
    t = conn.execute("SELECT * FROM tournaments WHERE id=?", (tournament_id,)).fetchone()
    if not t:
        conn.close()
        raise HTTPException(404, "Tournament not found")

    matches = conn.execute("""
        SELECT tm.*,
               a1.name as agent1_name, a1.domain as agent1_domain,
               a1.trust_score as agent1_trust, a1.battle_wins as agent1_wins,
               a2.name as agent2_name, a2.domain as agent2_domain,
               a2.trust_score as agent2_trust, a2.battle_wins as agent2_wins,
               aw.name as winner_name
        FROM tournament_matches tm
        JOIN agents a1 ON a1.id = tm.agent1_id
        JOIN agents a2 ON a2.id = tm.agent2_id
        LEFT JOIN agents aw ON aw.id = tm.winner_id
        WHERE tm.tournament_id = ?
        ORDER BY tm.round ASC, tm.match_num ASC
    """, (tournament_id,)).fetchall()
    conn.close()

    rounds: dict = {}
    for m in matches:
        r = m["round"]
        if r not in rounds:
            rounds[r] = []
        rounds[r].append(dict(m))

    return {
        **dict(t),
        "rounds": rounds,
        "total_rounds": max((m["round"] for m in matches), default=0),
    }


@router.get("/active/current")
def get_current_tournament():
    """Get the currently active tournament (most recent)."""
    conn = get_conn()
    t = conn.execute(
        "SELECT * FROM tournaments WHERE status='active' ORDER BY started_at DESC LIMIT 1"
    ).fetchone()
    if not t:
        conn.close()
        return None

    matches = conn.execute("""
        SELECT tm.*,
               a1.name as agent1_name, a1.domain as agent1_domain,
               a1.trust_score as agent1_trust, a1.battle_wins as agent1_wins,
               a2.name as agent2_name, a2.domain as agent2_domain,
               a2.trust_score as agent2_trust, a2.battle_wins as agent2_wins,
               aw.name as winner_name
        FROM tournament_matches tm
        JOIN agents a1 ON a1.id = tm.agent1_id
        JOIN agents a2 ON a2.id = tm.agent2_id
        LEFT JOIN agents aw ON aw.id = tm.winner_id
        WHERE tm.tournament_id = ?
        ORDER BY tm.round ASC, tm.match_num ASC
    """, (t["id"],)).fetchall()
    conn.close()

    rounds: dict = {}
    for m in matches:
        r = str(m["round"])
        if r not in rounds:
            rounds[r] = []
        rounds[r].append(dict(m))

    return {**dict(t), "rounds": rounds}


class StartTournament(BaseModel):
    domain: str = "any"
    name: str = ""


@router.post("/start")
async def start_tournament(body: StartTournament, authorization: str = Header(...)):
    """Admin: start a new weekly tournament. Picks 8 top agents for the domain."""
    token = authorization.removeprefix("Bearer ").strip()
    if token != ADMIN_TOKEN:
        user = get_user_by_token(token)
        if not user:
            raise HTTPException(403, "Admin only")

    domain = body.domain if body.domain != "any" else None
    conn = get_conn()

    # Pick 8 top agents by trust_score + battle_total for the domain
    if domain:
        rows = conn.execute("""
            SELECT * FROM agents WHERE status='active' AND domain=? AND name != 'CogitNewsBot'
            ORDER BY trust_score DESC, COALESCE(battle_total,0) DESC LIMIT 8
        """, (domain,)).fetchall()
        if len(rows) < 4:
            rows = conn.execute("""
                SELECT * FROM agents WHERE status='active' AND name != 'CogitNewsBot'
                ORDER BY trust_score DESC LIMIT 8
            """).fetchall()
    else:
        rows = conn.execute("""
            SELECT * FROM agents WHERE status='active' AND name != 'CogitNewsBot'
            ORDER BY trust_score DESC LIMIT 8
        """).fetchall()

    if len(rows) < 4:
        conn.close()
        raise HTTPException(400, "Not enough agents")

    agents = [dict(r) for r in rows[:8]]
    random.shuffle(agents)

    # Get current season number
    season_row = conn.execute("SELECT MAX(season) as s FROM tournaments").fetchone()
    season = (season_row["s"] or 0) + 1

    effective_domain = domain or "any"
    name = body.name or f"Season {season} · {effective_domain.title()} Championship"

    tid = str(uuid.uuid4())[:12]
    conn.execute(
        "INSERT INTO tournaments (id, name, domain, status, current_round, season) VALUES (?,?,?,?,?,?)",
        (tid, name, effective_domain, "active", 1, season),
    )

    # Build round 1 brackets (4 matches from 8 agents)
    questions = SEASON_QUESTIONS.get(effective_domain, SEASON_QUESTIONS["ai"])
    for i, (a1, a2) in enumerate(zip(agents[::2], agents[1::2])):
        mid = str(uuid.uuid4())[:8]
        conn.execute(
            "INSERT INTO tournament_matches (id, tournament_id, round, match_num, agent1_id, agent2_id) VALUES (?,?,?,?,?,?)",
            (mid, tid, 1, i + 1, a1["id"], a2["id"]),
        )

    conn.commit()
    conn.close()

    # Kick off round 1 battles in background
    asyncio.create_task(_run_round_battles(tid, 1, agents[::2], agents[1::2], questions))

    return {"tournament_id": tid, "name": name, "agents": len(agents), "rounds": 3}


async def _run_round_battles(tournament_id: str, round_num: int, agents1: list, agents2: list, questions: list):
    """Run battles for a tournament round and record winners."""
    import os
    groq_key = os.getenv("GROQ_API_KEY", "")

    for i, (a1, a2) in enumerate(zip(agents1, agents2)):
        q = questions[i % len(questions)]
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                # Advocate vs Critic
                r1, r2 = await asyncio.gather(
                    client.post(GROQ_URL,
                        headers={"Authorization": f"Bearer {groq_key}", "Content-Type": "application/json"},
                        json={"model": GROQ_MODEL,
                              "messages": [{"role": "system", "content": f"You are {a1['name']}, advocate position."},
                                           {"role": "user", "content": q}],
                              "max_tokens": 200, "temperature": 0.85}),
                    client.post(GROQ_URL,
                        headers={"Authorization": f"Bearer {groq_key}", "Content-Type": "application/json"},
                        json={"model": GROQ_MODEL,
                              "messages": [{"role": "system", "content": f"You are {a2['name']}, critic position."},
                                           {"role": "user", "content": q}],
                              "max_tokens": 200, "temperature": 0.85}),
                )
            # Use trust_score as tiebreaker (random element for fairness)
            score1 = a1.get("trust_score", 0.5) + random.uniform(-0.1, 0.1)
            score2 = a2.get("trust_score", 0.5) + random.uniform(-0.1, 0.1)
            winner = a1 if score1 >= score2 else a2

            conn = get_conn()
            conn.execute("""
                UPDATE tournament_matches SET winner_id=?, status='done'
                WHERE tournament_id=? AND round=? AND match_num=?
            """, (winner["id"], tournament_id, round_num, i + 1))

            # Create a real battle for this match
            battle_id = str(uuid.uuid4()).replace("-", "")[:16]
            ans1 = r1.json()["choices"][0]["message"]["content"].strip()
            ans2 = r2.json()["choices"][0]["message"]["content"].strip()

            conn.execute("INSERT INTO battles (id, question, domain, creator, summary) VALUES (?,?,?,?,?)",
                (battle_id, q, "tournament", "tournament",
                 f"{a1['name']} vs {a2['name']} — {winner['name']} advances to next round."))

            from backend.pipeline import process_post
            import uuid as _uuid
            for agent, ans, role in [(a1, ans1, "advocate"), (a2, ans2, "critic")]:
                pid = str(_uuid.uuid4())[:8]
                processed = process_post(ans, agent.get("domain", "other"))
                conn.execute("""
                    INSERT INTO posts (id, agent_id, domain, raw_insight, abstract, pattern_type,
                    embedding_domain, embedding_abstract, post_type, link_title)
                    VALUES (?,?,?,?,?,?,?,?,?,?)
                """, (pid, agent["id"], agent.get("domain","other"), ans,
                      processed["abstract"], processed["pattern_type"],
                      processed["embedding_domain"], processed["embedding_abstract"],
                      "qa", q[:200]))
                conn.execute("INSERT INTO battle_posts (id, battle_id, post_id, agent_id, agent_name, role) VALUES (?,?,?,?,?,?)",
                    (str(_uuid.uuid4())[:8], battle_id, pid, agent["id"], agent["name"], role))

            conn.execute("UPDATE tournament_matches SET battle_id=? WHERE tournament_id=? AND round=? AND match_num=?",
                (battle_id, tournament_id, round_num, i + 1))
            conn.execute("UPDATE agents SET battle_total=battle_total+1, battle_wins=battle_wins+? WHERE id=?",
                (1 if winner["id"] == a1["id"] else 0, a1["id"]))
            conn.execute("UPDATE agents SET battle_total=battle_total+1, battle_wins=battle_wins+? WHERE id=?",
                (1 if winner["id"] == a2["id"] else 0, a2["id"]))
            conn.commit()
            conn.close()

        except Exception as e:
            print(f"[Tournament] Match {i+1} error: {e}")


@router.post("/{tournament_id}/advance")
async def advance_tournament(tournament_id: str, authorization: str = Header(...)):
    """Admin: advance tournament to next round with winners."""
    token = authorization.removeprefix("Bearer ").strip()
    if token != ADMIN_TOKEN:
        raise HTTPException(403, "Admin only")

    conn = get_conn()
    t = conn.execute("SELECT * FROM tournaments WHERE id=?", (tournament_id,)).fetchone()
    if not t:
        conn.close()
        raise HTTPException(404)

    current_round = t["current_round"]
    # Get winners of current round
    winners_rows = conn.execute("""
        SELECT tm.winner_id, a.* FROM tournament_matches tm
        JOIN agents a ON a.id = tm.winner_id
        WHERE tm.tournament_id=? AND tm.round=? AND tm.status='done'
    """, (tournament_id, current_round)).fetchall()

    if not winners_rows:
        conn.close()
        raise HTTPException(400, "No completed matches in current round")

    winners = [dict(r) for r in winners_rows]
    if len(winners) < 2:
        # Final winner — close tournament
        conn.execute("UPDATE tournaments SET status='finished', current_round=? WHERE id=?",
                     (current_round, tournament_id))
        conn.commit()
        conn.close()
        return {"status": "finished", "champion": winners[0] if winners else None}

    next_round = current_round + 1
    random.shuffle(winners)
    questions = SEASON_QUESTIONS.get(t["domain"], SEASON_QUESTIONS["ai"])

    for i, (a1, a2) in enumerate(zip(winners[::2], winners[1::2])):
        mid = str(uuid.uuid4())[:8]
        conn.execute(
            "INSERT INTO tournament_matches (id, tournament_id, round, match_num, agent1_id, agent2_id) VALUES (?,?,?,?,?,?)",
            (mid, tournament_id, next_round, i + 1, a1["id"], a2["id"]),
        )

    conn.execute("UPDATE tournaments SET current_round=? WHERE id=?", (next_round, tournament_id))
    conn.commit()
    conn.close()

    asyncio.create_task(_run_round_battles(tournament_id, next_round, winners[::2], winners[1::2], questions))
    return {"advanced_to_round": next_round, "matches": len(winners) // 2}
